theme: jekyll-theme-slate
title: Elnaz
description: Hi I'm Elnaz, and I'm a MMath student at the University of Waterloo, Combinatorics and Optimization Department. My supervisor is Samuel Jaques and I'm interested in Cryptography. I completed my BSc (Mathematics Specialist) at the University of Toronto. 
