theme: jekyll-theme-slate
title: About
description: Hi! I'm Elnaz Hessami Pilehrood, and I'm a MMath student at the University of Waterloo, Department of Combinatorics and Optimization. My supervisor is Samuel Jaques and I'm interested in Cryptography. Before coming to Waterloo, I completed my BSc with a Mathematics Specialist at the University of Toronto. You can contact me at ehessami@uwaterloo.ca. 
